### ISSUE TITLE
[bug] Incorrect packpath is overwritten.

### ISSUE THREAD

**Issue by zutomayo147** [tani/vim-jetpack#106]
**Describe the bug**
wrong packpath 

**To Reproduce**
1. use the latest vim-jetpack

**Solution**
Delete code related to packpach in the benchmark folder

**Comment by hashue** [comment]
@zutomayo147 
Sorry, reproduce process and what how your feel to bug is ambiguous 
Can you teach us more detail like demo video etc...?

**Comment by zutomayo147** [comment]
![1](https://user-images.githubusercontent.com/42014197/209891862-accfbc14-80ba-42a0-8f17-83bd1b798bb2.png)

Sorry for the late reply. As of 12/29, with vim-jetpack, the packpath is as follows.

`packpath = ~/.local/share/nvim/site/pack/jetpack/src/vim-jetpack/benchmark
`

The packpath when vim-jetpack works properly is as follows.

  ```
packpath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/sh`
are/nvim/runtime,/usr/lib/nvim,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/afte
r,/etc/xdg/nvim/after,~/.config/nvim/afte
```

I thought the code about packpath in the benchmark folder in the vim-jetpack folder was the cause of this bug, so I removed them and it worked fine.

To reproduce this bug, delete the folder with the following path once and do jetpackSync.

`~/.local/share/nvim/site/pack`

**Comment by tani** [comment]
Thank you for reporting the issue. I understand that you have a problem caused by the `benchmark` directory. However, I could not reproduce your problem in my environment.
It means that I could not check that your issue will be solved by your proposal: removing the directory. Could you provide me the configuration example to reproduce for me?

**Comment by zutomayo147** [comment]
I think perhaps the way I installed vim-jetpack is the bug this time. I will report back as soon as I find the cause.

**Comment by zutomayo147** [comment]
Sorry for the very late response, I have changed the way I installed vim-jetpack and was able to resolve the problem in this issue. Please close this issue

**Comment by tani** [comment]
Thanks!
