### ISSUE TITLE
[bug] echo message when starting vim

### ISSUE THREAD

**Issue by hashitaku** [tani/vim-jetpack#107]
![Peek 2022-12-28 11-28](https://user-images.githubusercontent.com/34015121/209747973-a048d1cf-133c-4dc3-970b-3775ab46745d.gif)

I checked with git bisect and there seems to be a problem with commit 3b3f1b1a6e9cd0063622ec0990d16224b1b9897d

# env

vim-jetpack: main branch(dbf81823551ade78f918457ce4e72889cd5d9c41)
os: Linux archlinux 6.1.1-arch1-1
vim: vim 9.0.1046-1

# vimrc

```vim
source $VIMRUNTIME/defaults.vim

let s:jetpackfile = expand('<sfile>:p:h') .. '/pack/jetpack/opt/vim-jetpack/plugin/jetpack.vim'
let s:jetpackurl = "https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim"
if !filereadable(s:jetpackfile)
  call system(printf('curl -fsSLo %s --create-dirs %s', s:jetpackfile, s:jetpackurl))
endif

packadd vim-jetpack
call jetpack#begin()
call jetpack#add('tani/vim-jetpack', {'opt': 1})
call jetpack#end()
```

**Comment by hashue** [comment]
Hi @hashitaku 
I tried your minimal vimrc  but I didn't reproduce it ...

My Environment
OS macOS 
Vim Version

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov  5 2022 00:18:29)
macOS version - x86_64
Included patches: 1-639
````
https://user-images.githubusercontent.com/57579123/209882119-488365c8-281c-45d9-bb83-b0a39c856730.mov

**Comment by kawarimidoll** [comment]
I have same probrem.

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 26 2022 13:51:26)
macOS version - arm64
Included patches: 1-1100
Compiled by Homebrew
```

https://user-images.githubusercontent.com/8146876/209885848-08635219-d6c5-4a0b-b4a5-f18490fd68dd.mov
