### ISSUE TITLE
The progress bar displayed during the installation of the plugin will appear on the right side of the terminal.

### ISSUE THREAD

**Issue by torish14** [tani/vim-jetpack#11]
After reading this article, I switched from vim-plug and installed it.
[とても速いVimプラグインマネージャvim-jetpack](https://zenn.dev/dog/articles/jetpack_intro)

I was able to migrate without any problems by running `:JetpackSync`, but as the title says, the progress bar appears on the right side of the terminal.

![スクリーンショット 0004-02-19 5 33 27](https://user-images.githubusercontent.com/49876561/154758092-19b6ed7e-b481-454a-94c1-58e6a841f636.png)

Is there any way to make it appear on the left side?

Thank you!

**Comment by elianiva** [comment]
I'm pretty sure it respects your `splitright` option (judging from [these lines](https://stackoverflow.com/questions/22614280/vim-open-file-in-right-split/22614431)). You can set it to `nosplitright`.. which affects your entire split configuration. 

Maybe this plugin should `set nosplitright` before displaying the window and restore it back to the user's preference? I think this could be a better solution.

**Comment by tani** [comment]
Thank you for your suggestion.
I think @elianiva's method is the most appropriate to reproduce the behavior as demonstrated in the README. However, this method would deprive other users of the option to split the screen in a different way.

An easy way would be to add an option to the plugin to set the splitting method. But this is not the way of Vim-way. Can you give me more time?

**Comment by torish14** [comment]
@elianiva Thank you for your reply!
As you point out, the problem has been solved by modifying the `splitright` option.
