### ISSUE TITLE
When opt set to 1, plugin path not included in &rtp

### ISSUE THREAD

**Issue by leoatchina** [tani/vim-jetpack#112]
In my config, for some conflict reasons(may give raise to another issue), I set some `ZSaberLv0's` plugins  to `'opt': 1`
```
Jetpack 'ZSaberLv0/ZFVimJob', {'opt': 1}
Jetpack 'ZSaberLv0/ZFVimIgnore', {'opt': 1}
Jetpack 'ZSaberLv0/ZFVimDirDiff', {'opt': 1}
" zfvimim
if (Require('wubi') || Require('pinyin')) && g:has_terminal > 0
    Jetpack 'ZSaberLv0/ZFVimIM', {'opt': 1}
    if Require('wubi')
        Jetpack 'ZSaberLv0/ZFVimIM_wubi_base'
        let g:input_method = 'zfvim_wubi'
    else
        let g:input_method = 'zfvim_pinyin'
    endif
    Jetpack 'ZSaberLv0/ZFVimIM_pinyin'
endif
```
Then I found these plugins path not included in &rtp,  and some other plugins like `Leaderf` which may not be able to be merged, I can still  find their paths in &rtp. BTW, I installed plugins in a self-defined path.
![image](https://user-images.githubusercontent.com/4470821/213123744-c0ae5ed6-167d-49fa-8556-e2130a24c8ac.png)

**Comment by tani** [comment]
Thanks. `opt: 1` means that the plugin is not loaded (i.e., will not be added to rtp) until `packadd <package-name>`. So, it is not a problem. `merged: false` might help solving your problem. If you completed the issue without any problem, please close this issue. Best wishes,

**Comment by leoatchina** [comment]
Yes, my problem solved, thx!
