### ISSUE TITLE
Removed jetpack_ignore_patterns?

### ISSUE THREAD

**Issue by XeroOl** [tani/vim-jetpack#118]
I recently updated my vim, and it seems that vim-jetpack no longer creates or reads the `g:jetpack_ignore_patterns` variable.

Is this intended?

**Comment by tani** [comment]
yes. It has been deleted. Because Neovim came up with a faster and safer way than the merge mechanism. It is a cache mechanism called vim.loader. You can also use it with vim-jetpack! Please enjoy it.

**Comment by tani** [comment]
Cheers!
