### ISSUE TITLE
nvim-surround does not work

### ISSUE THREAD

**Issue by yusei-wy** [tani/vim-jetpack#119]
After installing nvim-surround with vim-jetpack, commands like `cs` `ds` did not work. (Only `ci` worked)

I switched the plugin manager to Packer and it worked, so it seems that vim-jetpack is affecting something. Is it possible to fix it?

```lua
vim.cmd('packadd vim-jetpack')
require('jetpack.packer').add {
    {'tani/vim-jetpack', opt = 1}, -- bootstrap

    {'cohama/lexima.vim'},
    {'airblade/vim-gitgutter'},
    {'kylechui/nvim-surround'}, -- not working
}
```

**Comment by tani** [comment]
Hello there! Thank you for using this plugin manager.

This issue usually occurs with Lua-implemented plugins, including nvim-surround and other nvim plugins. I apologize for any inconvenience this may have caused. It's possible that you might encounter a similar issue with other plugin managers, as most nvim plugins require calling the require('plugin-name').setup() method to enable them. However, no plugin manager executes this function automatically, so you need to do it separately.

For example, in vim-jetpack, you can add the following code to your configuration:

```lua
{ 'kylechui/nvim-surround',
  config = function()
    require('nvim-surround').setup({})
  end },
```

I hope this resolves the issue for you. Best regards.

**Comment by yusei-wy** [comment]
Thank you very much!
I was able to get nvim-surround to work using the method you taught me!
