### ISSUE TITLE
[Proposal] Make plugin list as global

### ISSUE THREAD

**Issue by kawarimidoll** [tani/vim-jetpack#13]
How about make plugin list `s:pkgs` as global, like `g:plugs` in vim-plug?
I believe it is useful to detect not-installed plugins. See tips in vim-plug wiki: https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation-of-missing-plugins

**Comment by tani** [comment]
If we expose the variable g:plugs like vim-plug, it will be difficult to change the internal data structure of the plugin in the future, which may affect the performance improvement in the future. Therefore, jetpack does not expose such variables, but exposes the function jetpack#tap() instead. This function checks whether a given plugin is installed or not.

**Comment by tani** [comment]
Thank you for the suggestion!

**Comment by kawarimidoll** [comment]
I see. Thank you for adding explanation 👍
