### ISSUE TITLE
About bootstrapping

### ISSUE THREAD

**Issue by xuanduc987** [tani/vim-jetpack#19]
Seems like the bootstrapping guide in README.md did not work.

From `:help packages`
> When Vim starts up, after processing your .vimrc, it scans all directories in
'packpath' for plugins under the "pack/*/start" directory. 

I think we must add `vim-jetpack` in `opt` folder, and then `packadd! vim-jetpack` before calling `jetpack#begin` like below

```sh
git clone --depth 1 https://github.com/tani/vim-jetpack ~/.vim/pack/jetpack/src/vim-jetpack && ln -s ~/.vim/pack/jetpack/{src,opt}/vim-jetpack
``` 
And in config file
```viml
packadd vim-jetpack
call jetpack#begin()
Jetpack 'tani/vim-jetpack', { 'opt': 1 }
call jetpack#end()
```

**Comment by tani** [comment]
That's true. Thank you for the professional comment. I'll update docs now.
