### ISSUE TITLE
E171 is occurred with installing fzf

### ISSUE THREAD

**Issue by kawarimidoll** [tani/vim-jetpack#2]
### Describe the bug

E171 is occurred with installing `fzf` by post-update hooks.

```
Running the post-update hooks ...
function jetpack#sync[8]..jetpack#postupdate[4]..<lambda>1[1]..fzf#install の処理中にエラーが検出されました:
行   10:
E605: 例外が捕捉されませんでした: /Users/kawarimidoll/.local/share/nvim/site/pack/jetpack/opt/_/install not found
function jetpack#sync[8]..jetpack#postupdate の処理中にエラーが検出されました:
行    4:
E171: :endif がありません
```

This is short demo:

![画面収録 2022-02-17 9 40 37](https://user-images.githubusercontent.com/8146876/154382048-bd4f85dc-e464-4d43-8aea-fa362573f40d.gif)

### To Reproduce

Start nvim with the config below and run `:JetpackSync`.

```vim
call jetpack#begin()
call jetpack#add( 'junegunn/fzf', { 'do': { -> fzf#install() } })
call jetpack#end()
```

### Output of `nvim --version`
```
❯ nvim --version 
NVIM v0.7.0-dev+920-g7e2ce35e3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by kawarimidoll@kawarimidoll-mini.local

Features: +acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/opt/homebrew/Cellar/neovim/HEAD-7e2ce35/share/nvim"

Run :checkhealth for more info
```

**Comment by tani** [comment]
Thank you for the issue. I maybe get the reason why this error has occurred.
1. Launch vim, jetpack calls `packadd _`
2. You type `JetpackSync` and jetpack runs the installation
3. jetpack bundle all package into `_`
4. jetpack runs `packaddall` to reload all plugins
5. jetpack runs post-update hooks.

Here, step 1 has already loads `_`, and thus, step 4 may not perform.
I will solve this issue as soon. Cheers!

**Comment by tani** [comment]
I hope my commit fixes this issue. Please check it. Thank you for using this software.

**Comment by kawarimidoll** [comment]
Thank you! Nice work 👍
