### ISSUE TITLE
[Feature Request] Add plugins infomation API

### ISSUE THREAD

**Issue by 4513ECHO** [tani/vim-jetpack#20]
I would like to add a global variable like [vim-plug's `g:plugs`](https://github.com/junegunn/vim-plug/wiki/api#global-variables-read-only). It helps other plugins such as [this](https://github.com/4513ECHO/vim-readme-viewer) to refer jetpack's infomation.

**Comment by 4513ECHO** [comment]
It seems that `s:pkgs` is used instead of `g:plugs` now. Only to rename that variable to global it resolves this issue.

**Comment by tani** [comment]
I agree with you that is very useful, however;

https://github.com/tani/vim-jetpack#is-it-possible-to-isntall-plugins-if-they-are-is-not-installed
> If we expose the variable g:plugs like vim-plug, it will be difficult to change the internal data structure of the plugin in the future, which may affect the performance improvement in the future. Therefore, jetpack does not expose such variables, but exposes the function jetpack#tap() instead. This function checks whether a given plugin is installed or not.

Hmm ... I want to give the best performance and stability users. Honestly, I cannot promise that there are no breaking change of the data structure in the future. Then, it is not the time to expose `s:pkgs`.

I agree what you say, however ...

**Comment by 4513ECHO** [comment]
I understood. Performance is important and the most amazing feature of jetpack. So, I have one suggestion. How about add the variable as **experimental** feature? No one can complain that you add breaking change. (If you say no, I will close this issue.)

**Comment by tani** [comment]
It is time to quote this, isn't it?

https://github.com/tani/vim-jetpack/blob/e992ba96ec827819ff8d34e4ab9a348c47914d13/doc/jetpack.txt#L62-L63

In a few days, I will refactor the data structure. After that, I will export the variable.
Please give me a few days.

**Comment by 4513ECHO** [comment]
Ok, thanks a lot! 😸

**Comment by hrsh7th** [comment]
The dein.vim has the `dein#get` API https://github.com/Shougo/dein.vim/blob/master/autoload/dein.vim#L46

**Comment by tani** [comment]
It's interesting. When we create such function, it is easy to keep the compatibility without any concern about internal data structure.

Let me consider making `jetpack#experimental_list()` and `jetpack#experimental_get()` to list up plugin names and retrieve plugin information, respectively.

**Comment by tani** [comment]
I added them on the experimental branch. Please check it.

https://github.com/tani/vim-jetpack/blob/641627a23a43fa652a3663b1f0c783f410049162/autoload/jetpack.vim#L409-L419

**Comment by 4513ECHO** [comment]
`jetpack#experimental_get()` should be return empty dict when `name` is wrong. It is same behaviour as dein.vim.

```diff
function! jetpack#experimental_list() abort
- return map(copy(s:pkgs), 'v:val["name"]')
+ return map(copy(s:pkgs), 'v:val.name')
endfunction

function! jetpack#experimental_get(name) abort
  for pkg in s:pkgs
    if pkg.name ==# a:name
      return pkg
    endif
  endfor
+ return {}
endfunction
```

**Comment by 4513ECHO** [comment]
It is shorter than now.

```vim
function! jetpack#experimental_get(name) abort
  let pkg = filter(copy(s:pkgs), printf('v:val.name ==# "%s"', a:name))
  " Note: lambda function version
  " let pkg = filter(copy(s:pkgs), { _, val -> val.name ==# a:name })
  return empty(pkg) ? {} pkg
endfunction
```

**Comment by tani** [comment]
I guess you do not need to `printf`.

```vim
function! jetpack#experimental_get(name) abort
  let pkg = filter(copy(s:pkgs), 'v:val.name ==# a:name')
  return empty(pkg) ? {} : pkg[0]
endfunction
```

Anyway, thank you for the suggestion. I'll update it.

**Comment by tani** [comment]
Finally, I have added `jetpack#names`, `jetpack#get`, and `jetpack#tap`!

https://github.com/tani/vim-jetpack/blob/e41052bda544b934f20f050d04f5a29a2fb9e9ad/doc/jetpack.txt#L66-L75

Thank you for the suggestion.

**Comment by 4513ECHO** [comment]
It looks nice! Thank you very much.
