### ISSUE TITLE
Feature request: Add `g:jetpack#ignore_patterns` and display why merge was disabled for each package

### ISSUE THREAD

**Issue by hrsh7th** [tani/vim-jetpack#28]
I think the `s:ignores` should be configurable because we can't support all of plugins files in central repo.

**Comment by tani** [comment]
I agree with you. If we export the variable, I would like to consider the suitable name of the variable. I means it is English problem. Which is more suitable as follows?
- `g:jetpack#ignore` (`.gitignore`, `.npmignore`)
- `g:jetpack#ignore_patterns`
- `g:jetpack#exclude` (`tsconfig.json`, `package.json`)
- `g:jetpack#exclude_patterns`

**Comment by tani** [comment]
Thank you for the suggesion! I have added that. Cheers,
