### ISSUE TITLE
Feature Request: allow using brackets without any options in packer style syntax

### ISSUE THREAD

**Issue by annenpolka** [tani/vim-jetpack#29]
In the current packer style syntax, bracketing a plugin name without options will result in an E715 error.

```lua
require('jetpack').startup(function(use)
  use { 'junegunn/fzf.vim' }
end)
```
```
Error detected while processing /home/username/.config/nvim/init.lua:
E5113: Error while calling lua chunk: Vim(let):E715: Dictionary required
stack traceback:
        [C]: in function 'jetpack#add'
        /home/username/.config/nvim/lua/jetpack.lua:27: in function 'use'
        /home/username/.config/nvim/init.lua:3: in function 'config'
        /home/username/.config/nvim/lua/jetpack.lua:15: in function 'startup'
        /home/username/.config/nvim/init.lua:2: in main chunk
Press ENTER or type command to continue
```

The above writing style is allowed in packer.nvim, which is useful if you plan to write out options later.

**Comment by tani** [comment]
Thank you for reporting to us. This should be allowed. I will fix this issue.

**Comment by annenpolka** [comment]
When I pass a Lua table with no key-value pairs to vimscript, it gets converted to an array.  Then `has_key()`, which takes a dictionary as an argument, triggers E715.
  
  I ran the following in command line mode to check the behavior.

```vim
:let table1 = luaeval("{'name'}")
:echo(table1)
:echo type(table1)
:echo has_key(table1, "key")
```
```vim
['name']
3
E715: Dictionary required
0
```

```vim
:let table2 = luaeval("{key = 'name'}")
:echo(table2)
:echo type(table2)
:echo has_key(table2, "key")
```
```vim
{'key': 'name'}
4
1
```

**Comment by tani** [comment]
@annenpolka Thanks. I have implemented this behavior. Please check branch #29.
If you have no problem, I'll close this issue. Cheers,

**Comment by tani** [comment]
I have confirmed that it works as well. Cheers!
