### ISSUE TITLE
[Question] how to resume vim option of `path`

### ISSUE THREAD

**Issue by younger-1** [tani/vim-jetpack#37]
When I want to use `gf` to goto filename under cursor, it can't take me to the file which is in then same directory of current file.
And I found `path` option don't inclue `.` which is necessary to find files in the same directory.
```vim
" set path?
  path=~/.config/nvim,~/.vim,~/.vim/pack/jetpack/opt/nerdtree,/usr/share/vim/vimfiles,~/.vim/pack/jetpack/opt/_,/usr/share/vim/vim82,~/.vim/pack/jetpack/opt/_/after,/usr/share/vim/vimfiles/after,~/.vim/after
```

In the image below, neither `startify` nor `startify.vim` work properly.
![图片](https://user-images.githubusercontent.com/45989017/156872795-971bfc47-70d1-4aee-9623-b6c77de63a95.png)

**Comment by younger-1** [comment]
The problem is I even can't `set path&` in `~/.vim/plugin/a.vim`!

**Comment by tani** [comment]
Try `autocmd VimEnter * let &path .= ','.getcwd()`. Cheers!

**Comment by younger-1** [comment]
Thx, this works for my case:
```vim
autocmd VimEnter * let &path .= ',.'
```

**Comment by younger-1** [comment]
May i ask how jetpack change the `path`? Because I didn't see anywhere `path` was changed in the source code

**Comment by tani** [comment]
I surely say vim-jetpack does not change `path`. For the proof, we can see that `path` contains `.` using the following example.

```vim
call jetpack#begin()
call jetpack#add('michaelb/do-nothing.vim')
call jetpack#end()
echomsg &path
```

Would you mind to show the **minimal** settings to reproduce your problem?

**Comment by younger-1** [comment]
Thanks for your information! It was caused by `vim-scriptease` :

https://github.com/tpope/vim-scriptease/blob/710fe7c2f3c636fae0b5cac041ff8da028a0777f/plugin/scriptease.vim#L117-L129

which calls this:

https://github.com/tpope/vim-scriptease/blob/710fe7c2f3c636fae0b5cac041ff8da028a0777f/autoload/scriptease.vim#L788-L790

**Comment by tani** [comment]
Ah! It's nice to inspect the reason. Tim's plugins are mostly fantastic, and however they oftenly breaks the Vim's default behaviour like this. Anyway, cheers!
