### ISSUE TITLE
[Bug]: `fzf.vim` do not work properly

### ISSUE THREAD

**Issue by younger-1** [tani/vim-jetpack#41]
## Minimal setup:

```vim
let g:jetpack#optimization = 2

call jetpack#begin()
  Jet 'https://github.com/junegunn/fzf', { 'do': { -> fzf#install() } }
  Jet 'https://github.com/junegunn/fzf.vim'
call jetpack#end()
```

## Expected behaviour

`FZF` command (defined by https://github.com/junegunn/fzf) and all command defined in https://github.com/junegunn/fzf.vim#commands
should work.

## Actual behaviour

1. `FZF` is not defined with the error message `Not an editor command`
2. None of commands in `fzf,vim` works, they all issue the error: `fzf#run function not found. You also need Vim plugin from the main fzf repository (i.e. junegunn/fzf *and* junegunn/fzf.vim)`

This is caused by the file `plugin/fzf.vim` in `fzf.vim` plugin overrides the file with the same name in `fzf` plugin:
https://github.com/junegunn/fzf.vim/blob/master/plugin/fzf.vim overrides
https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim

**Comment by tani** [comment]
Thank you for asking me. This is not a bug because I have already mentioned this problem in the document. Please read here https://github.com/tani/vim-jetpack/blob/e1a1b6496007c5095c68e3bdc700b755fa0ea9d8/doc/jetpack.txt#L107-L108.

Please set `let g:jetpack#optimization = 1`.

**Comment by younger-1** [comment]
Thanks for you pointing out that. Not related but I would like to know: did dein.vim handle this automaticlly?

**Comment by tani** [comment]
At least as I know, dein may overwrite them https://github.com/Shougo/dein.vim/blob/87a3c88f47c335714c8a76ba412c3b7c58a0212b/autoload/dein/install.vim#L442-L451

**Comment by tani** [comment]
`let g:jetpack#optimization = 1` mechanically manage duplicates. I recommend to use it.
