### ISSUE TITLE
Every syncing process, recompile and update everything from the ground up, ever if there wasn't any change pertaining to some of the plugins

### ISSUE THREAD

**Issue by z0xyz** [tani/vim-jetpack#54]
As the title says, the plugin doesn't ignore stagnant/unchanged plugins. That can be tolerable with mere vimscripts or pythons ones being merely pulled, but with post-installed hooks that requires compiling and building, it starts to become intimidating to update/sync the plugins.

**Comment by ryoppippi** [comment]
You can use `dir` option

**Comment by z0xyz** [comment]
Isn't there any other option except appending this option for every plugin ?

**Comment by XeroOl** [comment]
I don't think this should be default behavior.
My post-install hooks take a long time to run, and I would prefer not to recompile unless the source has actually changed.

**Comment by tani** [comment]
Hey, thank you for the discussion. I am happy to announce that the new vim-jetpack solves this issue. Please check it the [`alpha`](https://github.com/tani/vim-jetpack/tree/alpha) -branch. I will merge this this branch in July if it will be stable.

**Comment by z0xyz** [comment]
The featured `fzf` plugin keeps rebuilding `crats` every time i `JetpackSync`.

**Comment by tani** [comment]
Thank you for checking this issue. I found a bug that accidentally deletes directories in every installation. It has been solved a few minutes ago. I hope it works well. At least, it seems fine on my computer.

**Comment by z0xyz** [comment]
I should be the one thanking you for taking the time to resolve the issue. Thanks!
Hopefully it'll get merged soon.
