### ISSUE TITLE
Buffer has nonumber, but not norelativenumber

### ISSUE THREAD

**Issue by XeroOl** [tani/vim-jetpack#56]
The buffer created by JetpackSync removes line numbers, but not relative line numbers.

In my configuration, I have 'relativenumber' and 'signcolumn=yes', which takes up space here.
![image](https://user-images.githubusercontent.com/6820998/173962519-e86ce409-41eb-4fb8-a7ab-30ddac972cf1.png)

Maybe this is a minor complaint, but it would be nice if `norelativenumber` and `signcolumn=no` were set in the JetpackSync buffer.

**Comment by tani** [comment]
Thank you for the suggestion. I added them. Cheers!
