### ISSUE TITLE
line #L159 in jetpack.vim is wrong

### ISSUE THREAD

**Issue by leoatchina** [tani/vim-jetpack#57]
https://github.com/tani/vim-jetpack/blob/main/plugin/jetpack.vim#L159

I have modified it to `  to 80vnew +setlocal\ buftype=nofile\ nobuflisted\ nonumber\ norelativenumber\ signcolumn=no\ noswapfile\ nowrap JetpackStatus`

**Comment by tani** [comment]
Thank you for the information. I am interested in why you choose `80` to show the progress.
In my opinion, the total size of `username / reponame` is commonly less than 20. For example, the size of this repository `tani / vim-jetpack` is 16. So, I conclude 40 is enough. Cheers!

**Comment by tani** [comment]
Ah! I am sorry. I missed what you want to say. I got that you mentioned about the unneeded backslash `\ \nonumber`. I have fixed. Thank you so much!

**Comment by leoatchina** [comment]
Iprefer the procssed buffer on left side like Vim-plug

**Comment by tani** [comment]
Try `set nosplitright` in your `.vimrc` / `init.vim`
