### ISSUE TITLE
Add document about lua functions

### ISSUE THREAD

**Issue by ryoppippi** [tani/vim-jetpack#60]
@ryoppippi 
I'll add them to `doc/jetpack.txt` and `readme.md`

**Comment by tani** [comment]
I decide to remove `init()` function from new vim-jetpack because we can change the configuraiton parameters as follows.

```lua
vim.g.jetpack.ignore_patterns = {'/foo/bar'}
```

I feel it is more neovim-way. Would you mind to tell me your opinion?

**Comment by ryoppippi** [comment]
I think it looks ok. so I'll close this issue. Thanks
