### ISSUE TITLE
Post Update hooks running even when package isn't updated

### ISSUE THREAD

**Issue by XeroOl** [tani/vim-jetpack#68]
I have post-update hooks that take a long time to execute. For example, this plugin has a slow post-update hook:
```lua
use {'eraserhd/parinfer-rust',
    run = "cargo build --release",
}
```
This package does not update very often. I expect that the cargo command should run only when there is an actual change in the repository. However, it calls the hook every time I run `:JetpackSync`, regardless of whether the repository actually updated.

Because of this, `:JetpackSync` takes triple the amount of time to complete.

**Comment by XeroOl** [comment]
In vim-plug, `:PlugUpdate` will only run post-update hooks for repositories with changes, but `:PlugUpdate!` will run all of the post update hooks, regardless of whether the repository has changed. It might make sense to adopt something similar in vim-jetpack

**Comment by tani** [comment]
Hi, thank you for the suggestion. I merged the large update a few days ago.
The updates includes the solution of your problem. The latest vim-jetpack detects updates of repository and runs post-update hook if needed. That is smarter than before. Please update vim-jetpack. Cheers 🍻

**Comment by XeroOl** [comment]
I see! I guess I had bootstrapping set up incorrectly, because after re-downloading vim-jetpack manually, it's all working! Thank you very much for the help.

**Comment by tani** [comment]
Finally, I found the best way to provide the bootstrap installation.
Please read the latest README.md.
