### ISSUE TITLE
"file already exists" error when copying files

### ISSUE THREAD

**Issue by ryoppippi** [tani/vim-jetpack#70]
When I tried to use https://github.com/s1n7ax/nvim-window-picker, this error happens and the copying file stopped.
I know the reason.
There is a `screenshots` file in this repo. However, some other repos have a `screenshots` directory (like https://github.com/p00f/nvim-ts-rainbow). As a result, jetpack cannot make a `screenshots` directory.

**Comment by tani** [comment]
Thank you for reporting the issue. I believe that vim-jetpack should detect it and isolates the plugin automatically.  https://github.com/tani/vim-jetpack/blob/5664143a4aa569b3852f132f78bf196ee7e4d952/plugin/jetpack.vim#L337-L346

I would like to ask you some questions.

1. Is your computer macOS?
2. Please type `let g:jetpack_copy_method = 'copy'`. Do you still have problems?
3. What plugins are conflicted each other.

**Comment by ryoppippi** [comment]
Thank you.
Oh sorry, I had to report my settings.
This problem happened when `let g:jetpack_copy_method = 'symlinks'`.

So I would like to answer your question
1. yeah macOS 12
2. When I use `copy` there is still an error 
```
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: Vim(call):E739: Cannot create directory /Users/ryoppippi/.local/share/nvim/site/pack/jetpack/opt/_/screenshots: file already exists
stack traceback:
        [C]: in function 'sync'
        /Users/ryoppippi/.config/nvim/lua/plugin/init.lua:509: in function </Users/ryoppippi/.config/nvim/lua/plugin/init.lua:506>
Press ENTER or type command to continue
```

4. https://github.com/s1n7ax/nvim-window-picker and https://github.com/p00f/nvim-ts-rainbow

**Comment by tani** [comment]
I hope this issue can be closed today's updates. Please check it out. Cheers!

**Comment by tani** [comment]
Thank you for reporting this issue. Please reopen it if you have some problem.

**Comment by ryoppippi** [comment]
It was wonderful! Thank you!!
