### ISSUE TITLE
^@ signs in JetpackStaus

### ISSUE THREAD

**Issue by leoatchina** [tani/vim-jetpack#71]
Found on platforms `ubuntu20.04` and `windows10` ,  ~maybe it is caused by `git` command~
Only showed in `Already up to date.` lines

![image](https://user-images.githubusercontent.com/4470821/178089952-e15d2559-37f5-4309-84e2-388c9b330592.png)

**Comment by XeroOl** [comment]
I can confirm this on arch linux + NVIM v0.7.2 as well

**Comment by leoatchina** [comment]
repeated when set `g:jetpack_download_method = curl`
![image](https://user-images.githubusercontent.com/4470821/178090168-2cebf00a-cb83-4c81-bf9e-d2e7d9f468e8.png)

**Comment by leoatchina** [comment]
also `wget`
![image](https://user-images.githubusercontent.com/4470821/178090242-0ea82241-ae89-4683-89d3-de155a25ba68.png)

**Comment by tani** [comment]
Thank you for inspecting this issue. This is caused by null characters. I hope that this issue is closed now. Please check the latest commit. Cheers.

**Comment by leoatchina** [comment]
fixed in https://github.com/tani/vim-jetpack/commit/ef583aea8518bbcc1b92ab08a6be1749fac5ac0f
