### ISSUE TITLE
Lua run= flag warn on failed command.

### ISSUE THREAD

**Issue by XeroOl** [tani/vim-jetpack#89]
I am calling `vim.fn["jetpack#add"]("eraserhd/parinfer-rust", {run = "cargo build --release"})`. Unfortunately, I didn't realize that I don't have the `cargo` command installed on my computer.

`:JetpackSync` suceeded and didn't inform me that one of the hooks failed to run.

I think Jetpack should give a warning / message whenever one of these commands fails to run, or have some way to read the result of the run command.

**Comment by tani** [comment]
Thank you for the nice suggestion. It is theoritically possible by checking the exit status in the post-update phase. I am not familiar with the `job` module of Vim/Neovim. Please wait for a while to do that. I will send the message later.

**Comment by tani** [comment]
This issue is solved by the current revision. Please reopen this issue if you still have the issue. Thanks for the notification!
