### ISSUE TITLE
Lazy loading with same "event" on different plugins

### ISSUE THREAD

**Issue by Guergeiro** [tani/vim-jetpack#90]
If we register same command (and also same key) on multiple plugins, it stops working.

Not working:
```vim
call jetpack#begin(g:packages_home)

Jetpack 'habamax/vim-select', { 'on': ['Select'] }
Jetpack 'habamax/vim-select-more', { 'on': ['Select'] }

call jetpack#end()
```

Working
```vim
call jetpack#begin(g:packages_home)

Jetpack 'habamax/vim-select', { 'on': ['Select'] }
" Jetpack 'habamax/vim-select-more', { 'on': ['Select'] }

call jetpack#end()
```

For reference, I have the same configuration in vim-plug and works as expected.

**Comment by tani** [comment]
I hope that the latest commit solves your problem. Please check it.
Further, could you close this issue if it is solved. Thanks.

**Comment by Guergeiro** [comment]
Works as of [b0658a7](https://github.com/tani/vim-jetpack/commit/b0658a7710a8d34dbc39337e9ca6a7c92ad249b3)

**Comment by tani** [comment]
Great! Thank you for checking it :)
