### ISSUE TITLE
cmp-cmdline does not work on CmdEnter

### ISSUE THREAD

**Issue by tani** [tani/vim-jetpack#93]
@gw31415 said
> Thanks. I have confirmed that the error that appears on first startup is resolved.
> 
> However, I noticed that even after revision, cmp-cmdline is not working even after CmdlineEnter. It does not seem to be due to the order in which the plugins are loaded (confirmed by print debugging).
> 
> Here is vim-jetpack case: <img alt="image" width="588" src="https://user-images.githubusercontent.com/24710985/204122651-63dcd5de-de7e-4c5b-82d5-ca9714a16249.png">
> 
> Here is packer.nvim:case: <img alt="image" width="588" src="https://user-images.githubusercontent.com/24710985/204122459-61b751b1-d664-482e-b9b4-43510da1c5fb.png">
> 
> In the case of vim-jetpack, nvim-cmp is not shown. These tests is conducted in the containers mentioned in this comment.
> 
> > I created simple docker containers to check this behavior. [containers.tar.gz](https://github.com/tani/vim-jetpack/files/10095895/containers.tar.gz)
> > ```
> > containers
> > ├── jetpack
> > │   ├── Dockerfile
> > │   └── init.lua
> > └── packer
> >     ├── Dockerfile
> >     └── init.lua
> > ```
> 
> The first problem is solved, so I'm going to close this issue. Thank you very much.

**Comment by tani** [comment]
I will work on this issue next month.

**Comment by tani** [comment]
これが原因でした。cmp-cmdlineのafter/pluginが読み込まれていないため失敗しています。

> runtimepathには追加されるので、初期化時の:packaddなら問題ない。 [:help load-plugins](https://neovim.io/doc/user/starting.html#load-plugins)
つまり、以下のように初期化時の処理の最後に呼ばれる+{command}だと読み込まれない。


https://zenn.dev/notomo/articles/neovim-plugin-manager-optpack#%E5%88%9D%E6%9C%9F%E5%8C%96%E6%99%82%E4%BB%A5%E5%A4%96%E3%81%AB%3Apackadd%E3%81%97%E3%81%A6%E3%82%82after%2Fplugin%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%AF%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BE%E3%82%8C%E3%81%AA%E3%81%84

**Comment by tani** [comment]
I tought that this issue is inconsistent with respect to the loading order. I means that it may be never solved.

- On CmdEnter, `cmp-cmdline` is loaded. Then, `after/plugin` is also loaded by the lastet version of jetpack. In `after/plugin`, `cmp-cmdline` executes `require('cmp')`. Thus, `cmp` should be loaded before this plugin.
- On CmdEnter, `cmp` is loaded. Then, `config` is loaded immediately after the loading of this plugin. In `config`, the function executes `cmp.setup.cmdline`. Thus, `cmp-cmdline` should be loaded before this plugin.

This is the cyclic dependency. It theoretically is imposslble to solve such a depdency.
To solve this issue, you should load before VimEnter. I means that you should use the non-lazyloading.

**Comment by tani** [comment]
Please check the latest commit. I confirmed that it is solved. Thank you for the great contribution 🍻

**Comment by gw31415** [comment]
It worked properly with the latest version of the commit (ddbcbf2b).
Thanks for the fix!
