### ISSUE TITLE
Calling jetpack.tap before jetpack#end

### ISSUE THREAD

**Issue by XeroOl** [tani/vim-jetpack#96]
In previous versions, the lua API function `jetpack.tap` can be called before `jetpack#end`.
This is useful for configuration before a plugin is loaded.

Now, `jetpack.tap` crashes with the message:  `E5113: Error while calling lua chunk: Vim(return):E121: Undefined variable: s:available_packages`.

This should be enough `init.lua` to see the problem:
```lua
vim.cmd [[packadd vim-jetpack]]
local jetpack = require('jetpack')

vim.fn['jetpack#begin']()
vim.fn['jetpack#add']('tpope/vim-eunuch')

-- settings before plugin is loaded
if jetpack.tap('vim-eunuch') then -- ERROR: Undefined variable: s:available_packages
  vim.g.eunuch_no_maps = true
end

-- load plugins
vim.fn['jetpack#end']()
```

**Comment by tani** [comment]
Thanks for reporting it. I have fixed it with the latest commit. Please check it. If you still have a problem, do not hesitate to reopen this issue. Thanks.
