### ISSUE TITLE
non-opt plugins never be loaded

### ISSUE THREAD

**Issue by sotvokun** [tani/vim-jetpack#99]
The variable `s:available_packages` initializing is in the `jetpack#begin()` function.
https://github.com/tani/vim-jetpack/blob/6106cd51ac559e7e12c8f9d6164090546db29e72/plugin/jetpack.vim#L533-L535

But in the `jetpack#end()` function, the procedure to handle non-opt plugins calls the `s:available_packages()`.
https://github.com/tani/vim-jetpack/blob/6106cd51ac559e7e12c8f9d6164090546db29e72/plugin/jetpack.vim#L629-L631

The problem is the `s:available_packages()` returns the content in `available_packages.json` only if variable `s:available_packages` did not exist. The variable always exists after calling `jetpack#begin()`, so the code under the first return is unreachable, and this function always return an empty dictionary defined at `jetpack#begin()`.
https://github.com/tani/vim-jetpack/blob/6106cd51ac559e7e12c8f9d6164090546db29e72/plugin/jetpack.vim#L675-L684

**Comment by tani** [comment]
Hi, thank you for the reporting issue.
I found the solution and made a pull request to close this issue.
In a quarter of an hour, I will merge it. 
If you still have a problem, re-open this issue, please. Thanks.
